name: EternalReverie
version: '1.0'
main: com.nikoneko.eternalReverie.EternalReverie
api-version: '1.21'
depend: [Citizens]
commands:
  material-item:
    usage: /material-item <id> [amount]
  blueprint-item:
    usage: /blueprint-item <id> [amount]
  craft:
    description: Abre la mesa de fabricación de equipamiento.
    usage: /craft
  scrap:
    usage: /scrap <add|set|remove> <player> <value>
  remnants:
    usage: /remnants
  athanor:
    usage: /athanor
  give-food:
    usage: /give-food <internal-id>